#!/usr/bin/env bats

# Envisaged Redux
# Copyright (c) 2020 Carl Colena
#
# SPDX-License-Identifier: Apache-2.0

load common/bats_common


@test "System Tests" {
    COUNT=1
    # Init Condition
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" 

    # FPS
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" FPS="25"
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" FPS="30"
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" FPS="60"

    # Video Resolution & Border
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="480p" 
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="720p" 
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="1080p" 
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="1440p" 
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="2160p" 
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="480p" TEMPLATE="border"
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="720p" TEMPLATE="border"
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="1080p" TEMPLATE="border" 
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="1440p" TEMPLATE="border" 
    system_run GOURCE_TIME_SCALE="2.0" GOURCE_SECONDS_PER_DAY="0.01" VIDEO_RESOLUTION="2160p" TEMPLATE="border" 
}
