=== Runtime Mounts

In *Envisaged Redux*, mounts act both as a data source/sink, as well as a trigger to enable certain features. 
This section will describe some of the mounts that *Envisaged Redux* supports, as well as an example of a proper mount.

For safety reasons, all mounts that provide data to *Envisaged Redux* should be marked as `readonly` when using the `--mount` directive in Docker. 
This will be reflected in the examples.

[discrete]
===== Single/Multi Repos
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Read>>

| **<<Required>>**
| Yes

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/vcs_source(s)_dir#,dst=/visualization/resources/vcs_source,readonly`

| **<<Description>>**
a| Mounts the path to a single VCS repo, or a directory of multiple VCS repos in subdirectories for multi-repo visualizations.
Currently **Envisaged Redux** only supports Git repositories.

TIP: When running a multi-repo scenario, add `root` to <<_gource_hide_items,GOURCE_HIDE_ITEMS>> to visually separate multiple repos.
|===

===== Custom Log
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Read>>

| **<<Required>>**
| Yes

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/custom.log#,dst=/visualization/resources/gource.log,readonly`

| **<<Description>>**
a| **Envisaged Redux** will skip checks for a source repo and use the provided log file as the input to Gource.
|===

[discrete]
===== Captions
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Read>>

| **<<Required>>**
| No

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/captions.txt#,dst=/visualization/resources/captions.txt,readonly`

| **<<Description>>**
| Gource will try given captions.txt file to render captions on video. See {uri-gource-docs}[gource docs,window=_blank] for supported caption format.
|===

[discrete]
===== Avatars
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Read>>

| **<<Required>>**
| No

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/avatars_dir#,dst=/visualization/resources/avatars,readonly`

| **<<Description>>**
| Gource will try given avatars directory to render user avatars on video. See {uri-gource-docs}[gource docs,window=_blank] for naming rules and supported image types.
|===

[discrete]
===== Logo
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Read>>

| **<<Required>>**
| No

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/image.png#,dst=/visualization/resources/logo.image,readonly`

| **<<Description>>**
| Gource will try given logo image file to render the logo in the lower right hand corner of the video.
|===

[discrete]
===== Background Image
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Read>>

| **<<Required>>**
| No

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/image.png#,dst=/visualization/resources/background.image,readonly`

| **<<Description>>**
| Gource will try given background image file to use as the background of the visualization scene.
|===

[discrete]
===== Default User Image
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Read>>

| **<<Required>>**
| No

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/image.png#,dst=/visualization/resources/default_user.image,readonly`

| **<<Description>>**
a| Gource will try given image file to use as the default user image for all users in the visualization scene.

TIP: Add <<_gource_color_images,GOURCE_COLOR_IMAGES>> to have Gource apply a random color fill to each user with the given default image.
|===

[discrete]
===== Font File
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Read>>

| **<<Required>>**
| No

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/font.ttf#,dst=/visualization/resources/font,readonly`

| **<<Description>>**
| Gource will use the provided font file as the text font used in the visualization.
Compatible with most font types supported by FreeType, including `.ttf` and `.odf` formats.

|===

[discrete]
===== Output
[cols="15h,~", stripes=even, width=100%, grid=rows]
|===

| **<<MountType>>**
| <<Write>>

| **<<Required>>**
| No

| **<<MountExample>>**
a| `--mount type=bind,src=#/path/to/output_dir#,dst=/visualization/video`

| **<<Description>>**
| If this mount is made, *Envisaged Redux* will save the rendered video in the mounted directory and immediately exit once rendering completes.
|===