= Envisaged Redux
:description: Envisaged Redux
:doctype: article
:toc: left
:toclevels: 2
:sectlinks:
:linkattrs:
:imagesdir: resources/
:sectanchors:
:favicon: resources/favicon.ico

[.lead]
Version 
include::../VERSION[]

== About

*Envisaged Redux* is a Docker container application to generate visualizations of Git commit history. It does so using the power of Gource and FFmpeg.

What makes **Envisaged Redux** stand out from other similar containerized applications is its portable-focused approach. *Envisaged Redux* can and will run on any platform that supports Docker, and it requires no extra hardware support to run (e.g. GPU's). This enables *Envisaged Redux* to be used in CI/CD chains and basic cloud VPS services without issue. This is achieved by leveraging the Gallium LLVMPipe Driver and Xvfb to render in software.

Head over to link:#_getting_started[Getting Started] for a fast track tutorial.

Official source repository for this project is on https://gitlab.com/Cartoonman/Envisaged-Redux[Gitlab] with a mirror on https://github.com/Cartoonman/Envisaged-Redux[Github].


.Key features include: 
* Web-based Live Preview
* Gource API (via Environment Variables)
* Render Templates
* Multi-repository Support
* Recursive Submodule Support

*Envisaged Redux* is a fork of the https://github.com/utensils/Envisaged[Envisaged] project.

== Dependencies

A number of core dependencies used by *Envisaged Redux* are:

* FFmpeg &#8224;
* Gource &#8224;
* libx264 &#8224;
* libx265 &#8224;
* lighttpd
* Xvfb
* Mesa (Gallium LLVMPipe)
* ImageMagick
* HLS.js

&#8224; These projects are GPL Licensed to their respective copyright owners.
They are compiled from source during the `docker build` process and the source code is bundled with each image under `/gpl_sources`.
Compile-time configurations are derivable from the `Dockerfile` at the root of this project's source repository.

If there is any issue regarding GPL compliance, please reach out to the maintainer of this project.

=== Versioned Dependencies

For stability purposes, some dependencies (including some build-time dependencies) are version controlled for stability purposes.

The current list of versioned dependencies for **Envisaged Redux** 
include::../VERSION[]
are:

[source,docker]
----
include::../Dockerfile[tags=dep_versions]
----

include::sections/building.adoc[]

include::sections/getting-started.adoc[]

include::sections/api.adoc[]

include::sections/troubleshooting.adoc[]