== Getting Started

This section will fast track users to run a local instance of *Envisaged Redux* to experiment with. 
We will leverage example scripts designed to showcase the features of *Envisaged Redux*.
The *Envisaged Redux* git repository itself will be our example repository.
Users are encouraged to use these scripts to build off of and experiment with their own runtime configurations.

=== Installation


==== Dependancies
[horizontal]
Docker:: link:https://docs.docker.com/install/#supported-platforms[Installation Instructions]
Git:: link:https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Installation Instructions]

==== Fetching the Image

. Pull the latest build of *Envisaged Redux* from Docker Hub
+
--

[source,shell]
----
docker pull cartoonman/envisaged_redux:latest
----

--

. Clone the git repo for *Envisaged Redux*
+
--

[source,shell]
----
git clone https://gitlab.com/Cartoonman/Envisaged-Redux.git
----

--  
    

=== Quick Start Example

. Navigate to the cloned repo directory and run the following command:
+
--

.For Linux/Mac:
----
examples/quick_start.sh
----
.For Windows:
----
examples/quick_start.batch
----

--  

. At this point the container should be spawned. Open your browser and navigate to [http://localhost:8080]

. Click on `Click here for Live Preview` (or navigate to http://localhost:8080/preview.html) to view the Live Preview feature of *Envisaged Redux*. The Live Preview shows in pseudo-realtime (with a slowdown factor applied to avoid jitter) what the visualization being rendered looks like &#8224;.

. When the video is finished rendering, the main page will display the link to download the video from.
When you are done, simply press Ctrl + C in the terminal running *Envisaged Redux* and this will close the application.

TIP: The Live Preview window is smart and can tell when the *Envisaged Redux* container is stopped, or when a new *Envisaged Redux* container is launched.
A great way to experiment is to leave the Live Preview window up while playing with different runtime configurations.
The Live Preview window will automatically show the live preview when available without requiring browser refreshes.


&#8224; For more details on interpreting the output of Live Preview with respect to the rendered output video, see link:#_live_preview_details[Live Preview Details].

=== All Examples

Included in the `examples/` directory are a number of scripts that showcase different runtime configuration examples. 

quick_start::
+
--

If you followed the section link:#_Getting_Started[Getting Started], this is the example you ran.
This showcases a general example of configurations tailored for visualizing *Envisaged Redux*'s development history.
This enables the Live Preview functionality, as well as provides an example of using the Captions feature.

By default if the `--git-repo-dir` argument is not provided, it will use the *Envisaged Redux* repository, as well as add in the provided captions file to the render process. Adding a `--git-repo-dir` argument overrides this.

--

default::
+
--

This runs *Envisaged Redux* with no predefined environment variables.
This can be considered a clean slate example that users may wish to build on top of as they experiment.

--

preview::
+
--

If for any reason Live Preview does not work for you (e.g. browser not capable of https://en.wikipedia.org/wiki/HTTP_Live_Streaming[hls]), this is a useful script for running very short renders quickly.
Users can use this to quickly view the effects of their custom runtime configurations on the rendered visualization.

--


All of the included example scripts have a common API for interfacing with. 
They are easily extendable, and can be used out of the box for general experimentation.

CAUTION: All example scripts import functions from `examples/common.bash`. If you wish to move the scripts elsewhere, make sure you copy `common.bash` and place it in the same directory as the scripts.


.Avaliable Runtime Arguments for Example Scripts:
[source,txt]
----
include::../../examples/args.txt[]
----
