== Getting Started

This section will fast track users to run a local instance of *Envisaged Redux* to experiment with. 
We will leverage one of the many example scripts designed to showcase the features of *Envisaged Redux*.
The *Envisaged Redux* git repository itself will be our example repository.

=== Installation

==== Dependancies
[horizontal]
Docker:: link:https://docs.docker.com/install/#supported-platforms[Installation Instructions,window=_blank]
Git:: link:https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Installation Instructions,window=_blank]


=== Quick Start Example

==== Fetching the Image

. Pull the latest build of *Envisaged Redux* from Docker Hub
+
--

[source,shell]
----
docker pull cartoonman/envisaged-redux:latest
----

--

. Clone the git repo for *Envisaged Redux*
+
--

[source,shell]
----
git clone https://gitlab.com/Cartoonman/Envisaged-Redux.git
----

--  
    
==== Starting the Example

. Navigate to the cloned repo directory and run the following command:
+
--

----
examples/quick_start_example.sh
----

--  

. At this point the container should be spawned. Open your browser and navigate to http://localhost:8080[window=_blank]

. Click on `Click here for Live Preview` (or navigate to http://localhost:8080/preview.html[window=_blank]) to view the Live Preview feature of *Envisaged Redux*.
The Live Preview shows in pseudo-realtime (with a slowdown factor applied to avoid jitter) what the visualization being rendered looks like &#8224;.

. When the video is finished rendering, the main page will display the link to download the video from.
When you are done, simply press Ctrl + C in the terminal running *Envisaged Redux* and this will close the application.

TIP: The Live Preview window is smart and can tell when the *Envisaged Redux* container is stopped, or when a new *Envisaged Redux* container is launched.
A great way to experiment is to leave the Live Preview window up while playing with different runtime configurations.
The Live Preview window will automatically show the live preview when available without requiring browser refreshes.


NOTE: &#8224; Certain visual compression artifacts present/absent in output file will not be present/absent in the Live Preview display. 
See link:#_live_preview[Live Preview] for more details regarding these caveats.
